### ISSUE TITLE
ModuleNotFoundError when trying to import dislash

### ISSUE THREAD

**Issue by rf20008** [EQUENOS/dislash.py#57]
When trying to import dislash.py, a ModuleNotFoundError: No module named 'discord.webhook.async_' is raised.

Full traceback:
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import threading, dislash
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/__init__.py", line 4, in <module>
    from .interactions import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/interactions/__init__.py", line 1, in <module>
    from .interaction import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/interactions/interaction.py", line 13, in <module>
    from discord.webhook.async_ import WebhookMessage
ModuleNotFoundError: No module named 'discord.webhook.async_'

**Comment by rf20008** [comment]
This is an invalid issue
